# FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
FROM nvidia/cuda:12.2.2-devel-ubuntu22.04

RUN apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev

RUN ["ln", "-sf", "/usr/bin/python3", "/usr/bin/python"]
RUN ["ln", "-sf", "/usr/bin/pip3", "/usr/bin/pip"]

# pinning to the tested dev version, until the next release.
RUN pip install tensorrt_llm==0.8.0 -U --pre --extra-index-url https://pypi.nvidia.com

# installing packages required for our server code
RUN pip install flask flask_restful hydra-core tqdm pyyaml numpy

# bug fix https://github.com/NVIDIA/TensorRT-LLM/pull/1146
RUN pip install mpmath==1.3.0